apiVersion: v1
kind: ConfigMap
metadata:
  name: polardbx-scripts
  labels:
    {{- include "polardbx.labels" . | nindent 4 }}
data:
  replicaset-post-start.sh: |-
    {{- .Files.Get "scripts/replicaset-post-start.tpl" | nindent 4 }}